name: Build release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - run: npm install
    - run: npm --prefix functions install
    - run: npm run build:zip

    - name: Upload to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/*
        file_glob: true
        tag: ${{ github.ref }}
        overwrite: true

    - run: |
        export VERSION=$(node -e "console.log(require('./package.json').version)")
        export ZIP_NAME=spotify_lyrics-${VERSION}.zip
        export ZIP_PATH=build/${ZIP_NAME}
        echo "::set-env name=ZIP_NAME::${ZIP_NAME}"
        echo "::set-env name=ZIP_PATH::${ZIP_PATH}"

    # https://github.com/trmcnvn/firefox-addon
    - uses: trmcnvn/firefox-addon@v1
      with:
        uuid: '{d5bcc68d-856a-41e2-8021-d4c51f3b8e4a}'
        xpi: ${{ env.ZIP_PATH }}
        manifest: extension/manifest.json
        api-key: ${{ secrets.FIREFOX_API_KEY }}
        api-secret: ${{ secrets.FIREFOX_API_SECRET }}

    - uses: trmcnvn/chrome-addon@v2
      with:
        extension: mkjfooclbdgjdclepjeepbmmjaclipod
        zip: ${{ env.ZIP_PATH }}
        client-id: ${{ secrets.CHROME_CLIENT_ID }}
        client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
        refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
